# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
#Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np
array=np.random.randint(1,21,size=(5,5))
print("before array")

print(array)
np.fill_diagonal(array,0)
print("modified array:")
print(array)

before array
[[ 6 19 20 13  8]
 [18 18 12 20 15]
 [19 10  5 13 15]
 [19  6  3  5 13]
 [14 17  5 10 19]]
modified array:
[[ 0 19 20 13  8]
 [18  0 12 20 15]
 [19 10  0 13 15]
 [19  6  3  0 13]
 [14 17  5 10  0]]


In [5]:

##1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


array=np.arange(1,37).reshape((6,6))
print(array)
sub_array=array[2:5,1:4]
print(sub_array)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [7]:
2##. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

border_element=np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print("border element:")
print(border_element)

Original array:
[[ 6 11 16 20 10]
 [ 1  6  2 12 16]
 [16  8 10  9 18]
 [11 15  5 15  9]
 [ 1  1  8 14  6]]
border element:
[ 6 11 16 20 10  1  1  8 14  6  1 16 11 16 18  9]


In [11]:
#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
array1=np.random.randint(1,12,size=(3,4))
print("array1: ")
print(array1);
array2=np.random.randint(1,12,size=(3,4))
print("array2: ")
print(array2);
addition=array1+array2
print("addiion: ")
print(addition)
subtraction=array1-array2
print("subtraction:")
print(subtraction)
multiplication=array1*array2
print("multiplication:")
print(multiplication)
division=array1/array2
print("division:")
print(division)

array1: 
[[ 2  7  5 10]
 [ 1  8 11  3]
 [ 8  2  1  7]]
array2: 
[[ 3 10 10  3]
 [ 3  7  8  2]
 [ 8  5  4  8]]
addiion: 
[[ 5 17 15 13]
 [ 4 15 19  5]
 [16  7  5 15]]
subtraction:
[[-1 -3 -5  7]
 [-2  1  3  1]
 [ 0 -3 -3 -1]]
multiplication:
[[ 6 70 50 30]
 [ 3 56 88  6]
 [64 10  4 56]]
division:
[[0.66666667 0.7        0.5        3.33333333]
 [0.33333333 1.14285714 1.375      1.5       ]
 [1.         0.4        0.25       0.875     ]]


In [15]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
array=np.arange(1,17).reshape(4,4)
print("array:",array)
row_wise_sum=np.sum(array,axis=1)
coloumn_wise_sum=np.sum(array,axis=0)
print("row",row_wise_sum)
print("column",coloumn_wise_sum)

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row [10 26 42 58]
column [28 32 36 40]


In [17]:
#Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
array=np.random.randint(1,21,size=(5,5))
print("mean",np.mean(array))
print("median",np.median(array))
print("variation: ",np.var(array))

mean 11.0
median 11.0
variation:  36.4


In [19]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr=np.arange(1,10).reshape(3,3)
print(arr)
mean=np.mean(arr)
std_dev=np.std(arr)
normalized=(arr-mean)/std_dev
print("normilized array ",normalized)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
normilized array  [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [3]:
#Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
array=np.random.randint(1,11,size=(3,3))
row_array=np.random.randint(1,11,size=(3,))
print("original array: ",array)
print("row arrray: ",row_array)
result=array+row_array
print("result: ",result);

original array:  [[ 5 10  1]
 [ 8  8  6]
 [ 2  3  9]]
row arrray:  [8 2 9]
result:  [[13 12 10]
 [16 10 15]
 [10  5 18]]


In [5]:
# Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr=np.random.randint(1,21,size=(4,4))
row_arr=np.random.randint(1,21,size=(4,))
result=arr-row_arr[:,np.newaxis]
print("arr ",arr)
print("row arr: ",row_arr)
print("result",result)

arr  [[15 10  4 13]
 [17 10 13  6]
 [16  1 18 20]
 [14 15 11 19]]
row arr:  [ 2  5 18 13]
result [[ 13   8   2  11]
 [ 12   5   8   1]
 [ -2 -17   0   2]
 [  1   2  -2   6]]


In [8]:
#Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
data_type=[('name','U10'),('age','i4'),('weight','f4')]
data=np.array([('Alice',25,55.5),('Mohan',17,50.0),('Ravi',21,65.6),('Mayank',22,65.0)],dtype=data_type)
print("original array: ",data)
sorted_arr=np.sort(data,order='age')
print("sorted array: ",sorted_arr)

original array:  [('Alice', 25, 55.5) ('Mohan', 17, 50. ) ('Ravi', 21, 65.6)
 ('Mayank', 22, 65. )]
sorted array:  [('Mohan', 17, 50. ) ('Ravi', 21, 65.6) ('Mayank', 22, 65. )
 ('Alice', 25, 55.5)]


In [3]:
#Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
import numpy as np
data_type=[('x','i4'),('y','i4')]
data=np.array([(4,5),(6,8),(5,9)],dtype=data_type)
print("data : ",data)
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidian dis ",distances)

data :  [(4, 5) (6, 8) (5, 9)]
Euclidian dis  [[0.         3.60555128 4.12310563]
 [3.60555128 0.         1.41421356]
 [4.12310563 1.41421356 0.        ]]


In [5]:
#Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
import numpy.ma as ma
array=np.random.randint(1,21,size=(4,4))
masked_array=ma.masked_greater(array,10)
print("array: ",array)
print("masked array: ",masked_array)
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

array:  [[ 9  3  8  9]
 [ 3 10  2  3]
 [11 20  2  2]
 [ 3 15 13  2]]
masked array:  [[9 3 8 9]
 [3 10 2 3]
 [-- -- 2 2]
 [3 -- -- 2]]
Sum of unmasked elements: 56
