In [12]:
import numpy as np
#crreate array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [13]:
arr2=np.array([[2,3,4],[3,4,6],[7,8,9]])
arr2.shape

(3, 3)

In [16]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([13,45,65,65,44])
print(arr1+arr2)


[14 47 68 69 49]


In [22]:
#univarsal func
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [26]:
#array slicing and indexing
arr=np.array([[1,2,4],[5,6,8],[9,1,7]])
print(arr[1][2])
print(arr[0][2])
arr[1:,1:]

8
4


array([[6, 8],
       [1, 7]])

In [27]:
arr[0,0]=100
print(arr)

[[100   2   4]
 [  5   6   8]
 [  9   1   7]]


In [30]:
#Logical operator
data=np.array([1,3,4,5,7])
data>3
data[data>3]

array([4, 5, 7])

In [2]:
import pandas as pd

In [4]:
!pip install openpyxl

In [7]:
df_excel=pd.read_excel('data.xlsx')

In [8]:
df_excel.to_pickle('df_excel')

In [9]:
pd.read_pickle('df_excel')

Name  Age
0  Krish   32
1   Jack   34
2   John   31