In [1]:
import numpy as np
#crreate array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [2]:
arr2=np.array([[2,3,4],[3,4,6],[7,8,9]])
arr2.shape

(3, 3)

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
#vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([13,45,65,65,44])
print(arr1+arr2)


[14 47 68 69 49]


In [7]:
#univarsal func
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [19]:
#array slicing and indexing
arr=np.array([[1,2,4],[5,6,8],[9,1,7]])
print(arr[1][2])
print(arr[0][2])
arr[0:,1:]

8
4


array([[2, 4],
       [6, 8],
       [1, 7]])

In [9]:
arr[0,0]=100
print(arr)

[[100   2   4]
 [  5   6   8]
 [  9   1   7]]


In [10]:
#Logical operator
data=np.array([1,3,4,5,7])
data>3
data[data>3]

array([4, 5, 7])

In [11]:
import pandas as pd

In [12]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------

In [13]:
df_excel=pd.read_excel('data.xlsx')

In [14]:
df_excel.to_pickle('df_excel')

In [15]:
pd.read_pickle('df_excel')

,Name,Age
0,Krish,32
1,Jack,34
2,John,31
